import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Fredoka } from "next/font/google";

const fredoka = Fredoka({
  subsets: ["latin"],
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
      className={fredoka.className}
      >
        {children}
      </body>
    </html>
  );
}


// font Inter 
//  className={`${geistSans.variable} ${geistMono.variable} antialiased`}

